### ISSUE TITLE
Downloading not working with JDK16

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/nkod-isds#18]
```

2021-08-09 16:00:02 [main] ERROR c.s.x.b.v.r.reflect.opt.Injector - null
java.security.PrivilegedActionException: null
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:558)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:197)
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:179)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:285)
        at com.sun.xml.bind.v2.runtime.property.SingleElementNodeProperty.<init>(SingleElementNodeProperty.java:94)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:514)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:331)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
        at com.sun.xml.bind.api.JAXBRIContext.newInstance(JAXBRIContext.java:167)
        at com.sun.xml.bind.api.JAXBRIContext.newInstance(JAXBRIContext.java:111)
        at com.sun.xml.ws.developer.JAXBContextFactory$1.createJAXBContext(JAXBContextFactory.java:113)
        at com.sun.xml.ws.db.glassfish.JAXBRIContextFactory.newContext(JAXBRIContextFactory.java:94)
        at com.sun.xml.ws.spi.db.BindingContextFactory.getBindingContextFromSpi(BindingContextFactory.java:207)
        at com.sun.xml.ws.spi.db.BindingContextFactory.create(BindingContextFactory.java:176)
        at com.sun.xml.ws.model.AbstractSEIModelImpl$1.run(AbstractSEIModelImpl.java:222)
        at com.sun.xml.ws.model.AbstractSEIModelImpl$1.run(AbstractSEIModelImpl.java:195)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at com.sun.xml.ws.model.AbstractSEIModelImpl.createJAXBContext(AbstractSEIModelImpl.java:195)
        at com.sun.xml.ws.model.AbstractSEIModelImpl.postProcess(AbstractSEIModelImpl.java:110)
        at com.sun.xml.ws.model.RuntimeModeler.buildRuntimeModel(RuntimeModeler.java:324)
        at com.sun.xml.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:100)
        at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:74)
        at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:58)
        at com.sun.xml.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:120)
        at com.sun.xml.ws.client.WSServiceDelegate.buildRuntimeModel(WSServiceDelegate.java:882)
        at com.sun.xml.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:899)
        at com.sun.xml.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:862)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:451)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:420)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:402)
        at javax.xml.ws.Service.getPort(Service.java:169)
        at cz.czechpoint.isds.v20.DmInfoWebService.getDmInfoPortType(DmInfoWebService.java:56)
        at cz.opendata.mvcr.isds.AppEntry.createInfoPort(AppEntry.java:100)
        at cz.opendata.mvcr.isds.AppEntry.downloadMessages(AppEntry.java:81)
        at cz.opendata.mvcr.isds.AppEntry.main(AppEntry.java:73)
        at cz.opendata.mvcr.isds.AppEntry.main(AppEntry.java:50)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
        at java.base/java.lang.Class.getMethod(Class.java:2195)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:201)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        ... 45 common frames omitted
2021-08-09 16:00:02 [main] ERROR cz.opendata.mvcr.isds.AppEntry - Can't download messages.
com.sun.xml.ws.spi.db.DatabindingException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
```

**Comment by skodapetr** [comment]
Well as clearly stated in the requirements you need Java 12, so yes it is possible that the issue is with Java 16.

**Comment by jakubklimek** [comment]
Therefore, we need to update to JDK16
